import { typeSimNao } from '.';
import { iCliente } from './Cliente';
import { iProduto } from './Produto';
import { iVendedor } from './Vendedor';

export interface iItensList {
  REGISTRO: number;
  QTD: number;
  VALOR: number;
  CUSTO: number;
  TOTAL: number;
  CREDITO_GARANTIA: number;
  DATA_CREDITO: string;
  OBS_CREDITO: string;
  CFOP_ITEM: string;
  CST_ITEM: string;
  ITEM: number;
  TOTAL_CONTABIL: number;
  ICMS: number;
  IPI: number;
  IPI_PIPI: number;
  ST: number;
  SUBTOTAL: number;
  DESCONTO: number;
  TOTALIZADOR: string;
  CANCELADO: string;
  QTD_PAGO: number;
  PIS_CST: string;
  PIS_VBC: number;
  PIS_PPIS: number;
  PIS_VPIS: number;
  COFINS_CST: string;
  COFINS_VBC: number;
  COFINS_PCOFINS: number;
  COFINS_VCOFINS: number;
  MOTIVO_DEVOLUCAO: string;
  MOTIVO_GARANTIA: string;
  COMISSAO: number;
  TABELA: string;
  QTD_PEDIDO: number;
  BASECALCULOICMS: number;
  VALORICMS: number;
  BASECALCULOICMSST: number;
  VALORICMSST: number;
  BASEFECP: number;
  P_FECP: number;
  VALORFECP: number;
  BASEFECPST: number;
  P_FECPST: number;
  VALORFECPST: number;
  VALORFRETE: number;
  VALORSEGURO: number;
  VALORDESCONTO: number;
  VALORDESPESASACESSORIAS: number;
  VALORIPI: number;
  BASECALCULOIPI: number;
  VALORREDUCAOBC: number;
  TAXAREDUCAOBCST: number;
  VALOR_ACEITO: number;
  COMISSAO_INTERNO: number;
  CALCULO_BC_ST: number;
  CALCULO_ST: number;
  CALCULO_P_ICMS: number;
  QTD_GARANTIA_ENTREGUE: number;
  QTD_GARANTIA_SALDO: number;
  CST_ORIGINAL: string;
  CFOP_ORIGINAL: string;
  VENDEDOR: number;
  ID_VALE_CASCO: number;
  CONFERIDO: string;
  QTD_CONFERIDA: number;
  QUEM_CONFERIU: string;
  P_RED_BC_ICMS: number;
  GORDURA: number;
  REF_EMISSAO: string;
  REF_DOC: string;
  REF_DANFE: string;
  GNRE: string;
  FECP: number;
  ALIQ_II: number;
  VALORII: number;
  'MOVIMENTO@xdata.ref': string;
  PRODUTO: iProduto;
}

export interface iMovimento {
  MOVIMENTO: number;
  DATA: string;
  OFICINA: string;
  DOC: string;
  SUBTOTAL: number;
  ACRESCIMO: number;
  DESCONTO: number;
  TOTAL: number;
  AVISTA: number;
  TIPOAVISTA: string;
  APRAZO: number;
  TIPOAPRAZO: string;
  PRAZOS: string;
  TIPOMOV: 'PRE-VENDA' | 'VENDA' | 'DEVOLUCAO' | 'ACERTO';
  MOV: typeSimNao;
  ORIGEM: string;
  CANCELADO: typeSimNao;
  CAIXA: number;
  IMPRESSO: typeSimNao;
  CUPOM_FISCAL: string;
  MOTOBOY: number;
  OBS1: string;
  OBS2: string;
  COM_FRETE: string;
  FRETE: string;
  FRETE_RATEIO: string;
  COM_NOTA: string;
  OS: string;
  DATA_REF: string;
  MOTIVO_CANCELAMENTO: string;
  QUEM_CANCELOU: string;
  DATA_CANCELAMENTO: string;
  DATA_EMISSAO: string;
  MODELO_NOTA: string;
  SERIE_NOTA: string;
  CFOP_NOTA: string;
  BASECALCULOICMS: string;
  VALORICMS: string;
  BASECALCULOICMSST: string;
  VALORICMSST: string;
  VALORFECP: string;
  VALORFECPST: string;
  VALORFECPSTRet: string;
  VALORTOTALPRODUTOS: string;
  VALORFRETE: string;
  VALORSEGURO: string;
  VALORDESCONTO: string;
  VALORDESPESASACESSORIAS: string;
  VALORIPI: string;
  VALORII: string;
  VALORTOTALNOTA: string;
  ID_PAFECF: string;
  HORA: string;
  ECF: string;
  DAV: string;
  CCF: string;
  COO: string;
  PDV: string;
  TABELA: string;
  NOME_ADQUIRENTE: string;
  CNPJ_CPF: string;
  DANFE: string;
  TIPO_NF: string;
  ARQ_XML: string;
  DATA_ENTRADA: string;
  GNRE: string;
  FECP: string;
  CFOP_ESCRITURACAO: string;
  ENDERECO: string;
  ENDERECO_NUM: string;
  ENDERECO_CPL: string;
  BAIRRO: string;
  CIDADE: string;
  UF: string;
  CEP: string;
  IBGE_MUN: string;
  IBGE_CID: string;
  EXPEDICAO: string;
  TRANSPORTADORA: string;
  ID_MVE: string;
  ROTEIRO: string;
  STATUS: string;
  LOCAL_CONFERENCIA: string;
  VAI_CARREGAR: string;
  TRANS_QTD: string;
  PV_AGUARDAR: string;
  ID_OBS_NOTA: string;
  ENTREGA_SAIDA: string;
  ENTREGA_CHEGADA: string;
  REF_EMISSAO: string;
  REF_DOC: string;
  REF_DANFE: string;
  TIPO_CARREGA: string;
  DATA_COLETA: string;
  ID_PEDIDO: string;
  ANOTACAO: string;
  PROTOCOLO_NFE: string;
  IE: string;
  ID_NFCE: string;
  ID_CONDICAO_PGTO: string;
  ID_MECANICO: string;
  FRETE_POR_CONTA: string;
  MAIS_DIAS: string;
  LOCAL: string;
  ID_ARMAZEM: string;
  OBS_NF: string;
  PROGRAMA_FIDELIDADE: string;
  CNF: string;
  ID_PEDIDO_ECOMMERCE: string;
  LIDO: string;
  ID_TIPO_VENDA: string;
  Id_WMS: string;
  INTERMEDIADOR: string;
  INTERMEDIADOR_CNPJ: string;
  INTERMEDIADOR_ID: string;
  STATUS_INTEGRADOR: string;
  CLIENTE: iCliente;
  FORNECEDOR: string;
  VENDEDOR: iVendedor;
  VENDEDOR_TELEMARKETING?: iVendedor;
  VENDEDOR_VENDA_DIRETA?: iVendedor;
  REGISTRO_NF: string;
  ID_INTEGRADOR: string;
  Itens_List: iItensList[];
  Recebimento_List: string;
  Eventos_List: string;
}

export interface iItemPreVenda {
  CodigoProduto: string;
  Qtd: number;
  Valor: number;
  SubTotal: number;
  Frete: number;
  Desconto: number;
  Total: number;
  Tabela: string;
}
export interface iPreVenda {
  DataPedido: string;
  CodigoCliente: number;
  CodigoVendedor1: number;
  CodigoVendedor2?: number;
  SubTotal: number;
  ValorFrete?: number;
  Desconto?: number;
  Total: number;
  ObsPedido1: string;
  ObsPedido2?: string;
  ObsNotaFiscal: string;
  CodigoCondicaoPagamento: number;
  PedidoEcommerce?: string;
  ModeloNota: string;
  NumeroOrdemCompraCliente: string;
  Entrega: 'S' | 'N';
  TipoEntrega?: 'VEM BUSCAR' | 'CARRO';
  Origem?: string;
  Itens: iItemPreVenda[];
}

export interface iParcelasPgto {
  DIAS: number;
  VENCIMENTO: string;
  VALOR: number;
}

export interface iCondicaoPgto {
  ID: number;
  NOME: string;
  PARCELAS: number;
  VALOR_PARCELA: number;
  VALOR_MINIMO: number;
  PM: number;
  PZ01: number;
  PZ02: number;
  PZ03: number;
  PZ04: number;
  PZ05: number;
  PZ06: number;
  PZ07: number;
  PZ08: number;
  PZ09: number;
  PZ10: number;
  TIPO: string;
  DESTACAR_DESCONTO: string;
  FORMA: string;
}

export interface iFormaPgto {
  CARTAO: string;
}

export interface iTransportadora {
  FORNECEDOR: number;
  NOME: string;
  CIDADE: string;
}
